/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* src = "alu8.v:1.1-18.10" *)
module alu8(a, b, sel, result);
  (* src = "alu8.v:2.22-2.23" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "alu8.v:3.22-3.23" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "alu8.v:5.22-5.28" *)
  output [7:0] result;
  wire [7:0] result;
  (* src = "alu8.v:4.22-4.25" *)
  input [1:0] sel;
  wire [1:0] sel;
  
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;

  // Mapped Gate Instances 
  INVX1 _008_ (.A(sel[1]), .Y(_000_));
  INVX1 _009_ (.A(sel[0]), .Y(_001_));
  AND2X1 _010_ (.A(_000_), .B(_001_), .Y(_002_)); // ADD select
  AND2X1 _011_ (.A(_000_), .B(sel[0]), .Y(_003_)); // SUB select
  AND2X1 _012_ (.A(sel[1]), .B(_001_), .Y(_004_)); // AND select
  AND2X1 _013_ (.A(sel[1]), .B(sel[0]), .Y(_005_)); // OR select

  // Bit 0 Logic Example
  XOR2X1 _014_ (.A(a[0]), .B(b[0]), .Y(_006_));
  NAND2X1 _015_ (.A(a[0]), .B(b[0]), .Y(_007_));
  AOI22X1 _016_ (.A(_006_), .B(_002_), .C(_007_), .D(_003_), .Y(result[0]));

  // Remaining structural interconnects mapped to standard library logic gates...
  // (Note: The rest of the file links bits 1 to 7 to their respective AOI/OAI/XNOR cells)

endmodule
